<option value='en'>English</option>
<option value='af'>Afrikaans</option>
<option value='ar'>Arabic</option>
<option value='bg'>Bulgarian</option>
<option value='bn'>Bangla</option>
<option value='bs'>Bosnian</option>
<option value='ca'>Catalan</option>
<option value='cs'>Czech</option>
<option value='cy'>Welsh</option>
<option value='da'>Danish</option>
<option value='de'>German</option>
<option value='el'>Greek</option>
<option value='es'>Spanish</option>
<option value='et'>Estonian</option>
<option value='fa'>Persian</option>
<option value='fi'>Finnish</option>
<option value='fil'>Filipino</option>
<option value='fj'>Fijian</option>
<option value='fr'>French</option>
<option value='he'>Hebrew</option>
<option value='hi'>Hindi</option>
<option value='hr'>Croatian</option>
<option value='ht'>Haitian Creole</option>
<option value='hu'>Hungarian</option>
<option value='id'>Indonesian</option>
<option value='is'>Icelandic</option>
<option value='it'>Italian</option>
<option value='ja'>Japanese</option>
<option value='ko'>Korean</option>
<option value='lt'>Lithuanian</option>
<option value='lv'>Latvian</option>
<option value='mg'>Malagasy</option>
<option value='ms'>Malay</option>
<option value='mt'>Maltese</option>
<option value='mww'>Hmong Daw</option>
<option value='nb'>Norwegian</option>
<option value='nl'>Dutch</option>
<option value='otq'>Querétaro Otomi</option>
<option value='pl'>Polish</option>
<option value='pt'>Portuguese</option>
<option value='ro'>Romanian</option>
<option value='ru'>Russian</option>
<option value='sk'>Slovak</option>
<option value='sl'>Slovenian</option>
<option value='sm'>Samoan</option>
<option value='sr-Cyrl'>Serbian (Cyrillic)</option>
<option value='sr-Latn'>Serbian (Latin)</option>
<option value='sv'>Swedish</option>
<option value='sw'>Kiswahili</option>
<option value='ta'>Tamil</option>
<option value='te'>Telugu</option>
<option value='th'>Thai</option>
<option value='tlh'>Klingon</option>
<option value='to'>Tongan</option>
<option value='tr'>Turkish</option>
<option value='ty'>Tahitian</option>
<option value='uk'>Ukrainian</option>
<option value='ur'>Urdu</option>
<option value='vi'>Vietnamese</option>
<option value='yua'>Yucatec Maya</option>
<option value='yue'>Cantonese (Traditional)</option>
<option value='zh-Hans'>Chinese Simplified</option>
<option value='zh-Hant'>Chinese Traditional</option>